fix array handling

diff --git a/.github/workflows/generate-doi.yml b/.github/workflows/generate-doi.yml
--- a/.github/workflows/generate-doi.yml
+++ b/.github/workflows/generate-doi.yml
@@ -44,7 +44,12 @@ jobs:
           - name : Publish singularity files in batch
             shell: bash
             run: |
-              batch=$(echo '${{ matrix.app_batches.apps }}' | jq -r '.[]')
+              echo "Processing app_batches: ${{ matrix.app_batches }}"
+              if [ -z "${{ matrix.app_batches.apps }}" ]; then
+                echo "Error: app_batches.apps is empty or null."
+                exit 1
+              fi
+              batch=$(echo '[${{ matrix.app_batches.apps }}]' | jq -r '.[]')
               echo "Processing batches: ${batch[*]} "
               for app in $batch; do
                 echo "  Processing app: $app with ${#app[@]} apps"
